### ISSUE TITLE
Can you please build a verision for ruuning on MacOS?

### ISSUE THREAD

**Issue by AsicPrince** [iceland2k14/ETH_Hunt#11]
Hello, I really interesting in your codes for hunting keys. I wanna try my luck with my MacbookPro which has 64gb RAM. but your code only work with window (by .dll lib). Can you please make some change in your code so I can use them on MacOS like Dormant5 and bsgs. Thanks

**Comment by iceland2k14** [comment]
ETH_Hunt2 will use the gmp_ec which is based on gmpy2 library. It should work on MacOS. Although batch inverse is not added there so it maybe a little bit slower
